#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Example.Resource", IsApplication=true)]

namespace Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SlidingMenuLibrary.Resource.Attribute.behindOffset = global::Example.Resource.Attribute.behindOffset;
			global::SlidingMenuLibrary.Resource.Attribute.behindScrollScale = global::Example.Resource.Attribute.behindScrollScale;
			global::SlidingMenuLibrary.Resource.Attribute.behindWidth = global::Example.Resource.Attribute.behindWidth;
			global::SlidingMenuLibrary.Resource.Attribute.fadeDegree = global::Example.Resource.Attribute.fadeDegree;
			global::SlidingMenuLibrary.Resource.Attribute.fadeEnabled = global::Example.Resource.Attribute.fadeEnabled;
			global::SlidingMenuLibrary.Resource.Attribute.mode = global::Example.Resource.Attribute.mode;
			global::SlidingMenuLibrary.Resource.Attribute.selectorDrawable = global::Example.Resource.Attribute.selectorDrawable;
			global::SlidingMenuLibrary.Resource.Attribute.selectorEnabled = global::Example.Resource.Attribute.selectorEnabled;
			global::SlidingMenuLibrary.Resource.Attribute.shadowDrawable = global::Example.Resource.Attribute.shadowDrawable;
			global::SlidingMenuLibrary.Resource.Attribute.shadowWidth = global::Example.Resource.Attribute.shadowWidth;
			global::SlidingMenuLibrary.Resource.Attribute.touchModeAbove = global::Example.Resource.Attribute.touchModeAbove;
			global::SlidingMenuLibrary.Resource.Attribute.touchModeBehind = global::Example.Resource.Attribute.touchModeBehind;
			global::SlidingMenuLibrary.Resource.Attribute.viewAbove = global::Example.Resource.Attribute.viewAbove;
			global::SlidingMenuLibrary.Resource.Attribute.viewBehind = global::Example.Resource.Attribute.viewBehind;
			global::SlidingMenuLibrary.Resource.Id.fullscreen = global::Example.Resource.Id.fullscreen;
			global::SlidingMenuLibrary.Resource.Id.left = global::Example.Resource.Id.left;
			global::SlidingMenuLibrary.Resource.Id.margin = global::Example.Resource.Id.margin;
			global::SlidingMenuLibrary.Resource.Id.none = global::Example.Resource.Id.none;
			global::SlidingMenuLibrary.Resource.Id.right = global::Example.Resource.Id.right;
			global::SlidingMenuLibrary.Resource.Id.selected_view = global::Example.Resource.Id.selected_view;
			global::SlidingMenuLibrary.Resource.Id.slidingmenumain = global::Example.Resource.Id.slidingmenumain;
			global::SlidingMenuLibrary.Resource.Layout.slidingmenumain = global::Example.Resource.Layout.slidingmenumain;
			global::SlidingMenuLibrary.Resource.String.ApplicationName = global::Example.Resource.String.ApplicationName;
			global::SlidingMenuLibrary.Resource.String.Hello = global::Example.Resource.String.Hello;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu = global::Example.Resource.Styleable.SlidingMenu;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_behindOffset = global::Example.Resource.Styleable.SlidingMenu_behindOffset;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_behindScrollScale = global::Example.Resource.Styleable.SlidingMenu_behindScrollScale;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_behindWidth = global::Example.Resource.Styleable.SlidingMenu_behindWidth;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_fadeDegree = global::Example.Resource.Styleable.SlidingMenu_fadeDegree;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_fadeEnabled = global::Example.Resource.Styleable.SlidingMenu_fadeEnabled;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_mode = global::Example.Resource.Styleable.SlidingMenu_mode;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_selectorDrawable = global::Example.Resource.Styleable.SlidingMenu_selectorDrawable;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_selectorEnabled = global::Example.Resource.Styleable.SlidingMenu_selectorEnabled;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_shadowDrawable = global::Example.Resource.Styleable.SlidingMenu_shadowDrawable;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_shadowWidth = global::Example.Resource.Styleable.SlidingMenu_shadowWidth;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_touchModeAbove = global::Example.Resource.Styleable.SlidingMenu_touchModeAbove;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_touchModeBehind = global::Example.Resource.Styleable.SlidingMenu_touchModeBehind;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_viewAbove = global::Example.Resource.Styleable.SlidingMenu_viewAbove;
			global::SlidingMenuLibrary.Resource.Styleable.SlidingMenu_viewBehind = global::Example.Resource.Styleable.SlidingMenu_viewBehind;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070001
			public const int birds = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int birds_img = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int color_names = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080004
			public const int black = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int blue = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int green = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int red = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int white = 2131230723;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090001
			public const int list_padding = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int shadow_width = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int slidingmenu_offset = 2131296256;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int eagle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flamingo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int heron = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_github = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int indicator = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int new_indicator = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int octocat = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int octocat_scaled = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ostrich = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int peacock = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int penguin = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int shadow = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int shadowright = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int toucan = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int turkey = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int vulture = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001f
			public const int about = 2131034143;
			
			// aapt resource value: 0x7f050016
			public const int behind_width = 2131034134;
			
			// aapt resource value: 0x7f050021
			public const int contact = 2131034145;
			
			// aapt resource value: 0x7f050006
			public const int content_frame = 2131034118;
			
			// aapt resource value: 0x7f05001a
			public const int fade_degree = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int fade_enabled = 2131034137;
			
			// aapt resource value: 0x7f050003
			public const int fullscreen = 2131034115;
			
			// aapt resource value: 0x7f05001e
			public const int github = 2131034142;
			
			// aapt resource value: 0x7f050007
			public const int github_button = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int grid_item_img = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int left = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int left_right = 2131034125;
			
			// aapt resource value: 0x7f050020
			public const int licenses = 2131034144;
			
			// aapt resource value: 0x7f050004
			public const int margin = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int menu_frame = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int menu_frame_two = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int mode = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int none = 2131034117;
			
			// aapt resource value: 0x7f05000b
			public const int pager = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int right = 2131034114;
			
			// aapt resource value: 0x7f05001b
			public const int row_icon = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int row_title = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int scroll_scale = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int selected_view = 2131034112;
			
			// aapt resource value: 0x7f050017
			public const int shadow_enabled = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int shadow_width = 2131034136;
			
			// aapt resource value: 0x7f05001d
			public const int slidingmenumain = 2131034141;
			
			// aapt resource value: 0x7f05000e
			public const int touch_above = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int touch_above_full = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int touch_above_margin = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int touch_above_none = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int touch_behind = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int touch_behind_full = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int touch_behind_margin = 2131034132;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int num_cols = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int content_frame = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int github_button = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int grid_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list_grid = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int menu_frame = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int menu_frame_two = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int pager = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int properties = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int responsive_content_frame = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int row = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int slidingmenumain = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int example_list = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int main = 2131492865;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060018
			public const int about = 2131099672;
			
			// aapt resource value: 0x7f06001b
			public const int about_msg = 2131099675;
			
			// aapt resource value: 0x7f06000d
			public const int anim_fold = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int anim_scale = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int anim_slide = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int anim_zoom = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int animations = 2131099658;
			
			// aapt resource value: 0x7f06001c
			public const int apache_license = 2131099676;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int attach = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int changing_fragments = 2131099663;
			
			// aapt resource value: 0x7f06001a
			public const int contact = 2131099674;
			
			// aapt resource value: 0x7f060004
			public const int general = 2131099652;
			
			// aapt resource value: 0x7f060014
			public const int github = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int github_label = 2131099669;
			
			// aapt resource value: 0x7f060011
			public const int left = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int left_and_right = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int licenses = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int no_email = 2131099677;
			
			// aapt resource value: 0x7f060003
			public const int properties = 2131099651;
			
			// aapt resource value: 0x7f060017
			public const int responsive_explanation = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int responsive_ui = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int right = 2131099666;
			
			// aapt resource value: 0x7f060007
			public const int title_bar = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int title_bar_content = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int title_bar_slide = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int viewpager = 2131099653;
			
			// aapt resource value: 0x7f060016
			public const int what_is_this = 2131099670;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0000
			public const int ExampleTheme = 2131427328;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int main = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
