#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidFlowLayout.Resource", IsApplication=false)]

namespace AndroidFlowLayout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int debugDraw = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int layoutDirection = 2130771968;
			
			// aapt resource value: 0x7f010003
			public static int layout_newLine = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int layout_weight = 2130771972;
			
			// aapt resource value: 0x7f010002
			public static int weightDefault = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int ltr = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int rtl = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ApplicationName = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int Hello = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlowLayout = new int[] {
					16842927,
					16842948,
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public static int FlowLayout_android_gravity = 0;
			
			// aapt resource value: 1
			public static int FlowLayout_android_orientation = 1;
			
			// aapt resource value: 3
			public static int FlowLayout_debugDraw = 3;
			
			// aapt resource value: 2
			public static int FlowLayout_layoutDirection = 2;
			
			// aapt resource value: 4
			public static int FlowLayout_weightDefault = 4;
			
			public static int[] FlowLayout_LayoutParams = new int[] {
					16842931,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public static int FlowLayout_LayoutParams_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public static int FlowLayout_LayoutParams_layout_newLine = 1;
			
			// aapt resource value: 2
			public static int FlowLayout_LayoutParams_layout_weight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
