#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidStaggeredGrid.Resource", IsApplication=false)]

namespace AndroidStaggeredGrid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int column_count = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int column_count_landscape = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int column_count_portrait = 2130771969;
			
			// aapt resource value: 0x7f010007
			public static int grid_paddingBottom = 2130771975;
			
			// aapt resource value: 0x7f010004
			public static int grid_paddingLeft = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int grid_paddingRight = 2130771973;
			
			// aapt resource value: 0x7f010006
			public static int grid_paddingTop = 2130771974;
			
			// aapt resource value: 0x7f010003
			public static int item_margin = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public static int ApplicationName = 2130837505;
			
			// aapt resource value: 0x7f020000
			public static int Hello = 2130837504;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] StaggeredGridView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public static int StaggeredGridView_column_count = 0;
			
			// aapt resource value: 2
			public static int StaggeredGridView_column_count_landscape = 2;
			
			// aapt resource value: 1
			public static int StaggeredGridView_column_count_portrait = 1;
			
			// aapt resource value: 7
			public static int StaggeredGridView_grid_paddingBottom = 7;
			
			// aapt resource value: 4
			public static int StaggeredGridView_grid_paddingLeft = 4;
			
			// aapt resource value: 5
			public static int StaggeredGridView_grid_paddingRight = 5;
			
			// aapt resource value: 6
			public static int StaggeredGridView_grid_paddingTop = 6;
			
			// aapt resource value: 3
			public static int StaggeredGridView_item_margin = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
