#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MaterialDesignLibrary.Example.Resource", IsApplication=true)]

namespace MaterialDesignLibrary.Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MaterialDesignLibrary.Resource.Animation.dialog_main_hide_amination = global::MaterialDesignLibrary.Example.Resource.Animation.dialog_main_hide_amination;
			global::MaterialDesignLibrary.Resource.Animation.dialog_main_show_amination = global::MaterialDesignLibrary.Example.Resource.Animation.dialog_main_show_amination;
			global::MaterialDesignLibrary.Resource.Animation.dialog_root_hide_amin = global::MaterialDesignLibrary.Example.Resource.Animation.dialog_root_hide_amin;
			global::MaterialDesignLibrary.Resource.Animation.dialog_root_show_amin = global::MaterialDesignLibrary.Example.Resource.Animation.dialog_root_show_amin;
			global::MaterialDesignLibrary.Resource.Animation.progress_indeterminate_animation = global::MaterialDesignLibrary.Example.Resource.Animation.progress_indeterminate_animation;
			global::MaterialDesignLibrary.Resource.Animation.snackbar_hide_animation = global::MaterialDesignLibrary.Example.Resource.Animation.snackbar_hide_animation;
			global::MaterialDesignLibrary.Resource.Animation.snackbar_show_animation = global::MaterialDesignLibrary.Example.Resource.Animation.snackbar_show_animation;
			global::MaterialDesignLibrary.Resource.Attribute.animate = global::MaterialDesignLibrary.Example.Resource.Attribute.animate;
			global::MaterialDesignLibrary.Resource.Attribute.check = global::MaterialDesignLibrary.Example.Resource.Attribute.check;
			global::MaterialDesignLibrary.Resource.Attribute.checkBoxSize = global::MaterialDesignLibrary.Example.Resource.Attribute.checkBoxSize;
			global::MaterialDesignLibrary.Resource.Attribute.clickAfterRipple = global::MaterialDesignLibrary.Example.Resource.Attribute.clickAfterRipple;
			global::MaterialDesignLibrary.Resource.Attribute.iconDrawable = global::MaterialDesignLibrary.Example.Resource.Attribute.iconDrawable;
			global::MaterialDesignLibrary.Resource.Attribute.iconSize = global::MaterialDesignLibrary.Example.Resource.Attribute.iconSize;
			global::MaterialDesignLibrary.Resource.Attribute.max = global::MaterialDesignLibrary.Example.Resource.Attribute.max;
			global::MaterialDesignLibrary.Resource.Attribute.min = global::MaterialDesignLibrary.Example.Resource.Attribute.min;
			global::MaterialDesignLibrary.Resource.Attribute.progress = global::MaterialDesignLibrary.Example.Resource.Attribute.progress;
			global::MaterialDesignLibrary.Resource.Attribute.ringWidth = global::MaterialDesignLibrary.Example.Resource.Attribute.ringWidth;
			global::MaterialDesignLibrary.Resource.Attribute.rippleBorderRadius = global::MaterialDesignLibrary.Example.Resource.Attribute.rippleBorderRadius;
			global::MaterialDesignLibrary.Resource.Attribute.rippleColor = global::MaterialDesignLibrary.Example.Resource.Attribute.rippleColor;
			global::MaterialDesignLibrary.Resource.Attribute.rippleSpeed = global::MaterialDesignLibrary.Example.Resource.Attribute.rippleSpeed;
			global::MaterialDesignLibrary.Resource.Attribute.showNumberIndicator = global::MaterialDesignLibrary.Example.Resource.Attribute.showNumberIndicator;
			global::MaterialDesignLibrary.Resource.Attribute.thumbSize = global::MaterialDesignLibrary.Example.Resource.Attribute.thumbSize;
			global::MaterialDesignLibrary.Resource.Attribute.value = global::MaterialDesignLibrary.Example.Resource.Attribute.value;
			global::MaterialDesignLibrary.Resource.Color.green = global::MaterialDesignLibrary.Example.Resource.Color.green;
			global::MaterialDesignLibrary.Resource.Color.thumbColor = global::MaterialDesignLibrary.Example.Resource.Color.thumbColor;
			global::MaterialDesignLibrary.Resource.Drawable.background_button = global::MaterialDesignLibrary.Example.Resource.Drawable.background_button;
			global::MaterialDesignLibrary.Resource.Drawable.background_button_float = global::MaterialDesignLibrary.Example.Resource.Drawable.background_button_float;
			global::MaterialDesignLibrary.Resource.Drawable.background_button_rectangle = global::MaterialDesignLibrary.Example.Resource.Drawable.background_button_rectangle;
			global::MaterialDesignLibrary.Resource.Drawable.background_checkbox = global::MaterialDesignLibrary.Example.Resource.Drawable.background_checkbox;
			global::MaterialDesignLibrary.Resource.Drawable.background_checkbox_check = global::MaterialDesignLibrary.Example.Resource.Drawable.background_checkbox_check;
			global::MaterialDesignLibrary.Resource.Drawable.background_checkbox_uncheck = global::MaterialDesignLibrary.Example.Resource.Drawable.background_checkbox_uncheck;
			global::MaterialDesignLibrary.Resource.Drawable.background_progress = global::MaterialDesignLibrary.Example.Resource.Drawable.background_progress;
			global::MaterialDesignLibrary.Resource.Drawable.background_switch_ball_uncheck = global::MaterialDesignLibrary.Example.Resource.Drawable.background_switch_ball_uncheck;
			global::MaterialDesignLibrary.Resource.Drawable.background_transparent = global::MaterialDesignLibrary.Example.Resource.Drawable.background_transparent;
			global::MaterialDesignLibrary.Resource.Drawable.dialog_background = global::MaterialDesignLibrary.Example.Resource.Drawable.dialog_background;
			global::MaterialDesignLibrary.Resource.Drawable.float_button1_shadowp = global::MaterialDesignLibrary.Example.Resource.Drawable.float_button1_shadowp;
			global::MaterialDesignLibrary.Resource.Drawable.float_button_shadow1 = global::MaterialDesignLibrary.Example.Resource.Drawable.float_button_shadow1;
			global::MaterialDesignLibrary.Resource.Drawable.ic_launcher = global::MaterialDesignLibrary.Example.Resource.Drawable.ic_launcher;
			global::MaterialDesignLibrary.Resource.Drawable.ic_reloj_max = global::MaterialDesignLibrary.Example.Resource.Drawable.ic_reloj_max;
			global::MaterialDesignLibrary.Resource.Drawable.shadow_down = global::MaterialDesignLibrary.Example.Resource.Drawable.shadow_down;
			global::MaterialDesignLibrary.Resource.Drawable.shadow_right = global::MaterialDesignLibrary.Example.Resource.Drawable.shadow_right;
			global::MaterialDesignLibrary.Resource.Drawable.sprite_check = global::MaterialDesignLibrary.Example.Resource.Drawable.sprite_check;
			global::MaterialDesignLibrary.Resource.Id.blue = global::MaterialDesignLibrary.Example.Resource.Id.blue;
			global::MaterialDesignLibrary.Resource.Id.button_accept = global::MaterialDesignLibrary.Example.Resource.Id.button_accept;
			global::MaterialDesignLibrary.Resource.Id.button_cancel = global::MaterialDesignLibrary.Example.Resource.Id.button_cancel;
			global::MaterialDesignLibrary.Resource.Id.buttonflat = global::MaterialDesignLibrary.Example.Resource.Id.buttonflat;
			global::MaterialDesignLibrary.Resource.Id.contentDialog = global::MaterialDesignLibrary.Example.Resource.Id.contentDialog;
			global::MaterialDesignLibrary.Resource.Id.contentSelector = global::MaterialDesignLibrary.Example.Resource.Id.contentSelector;
			global::MaterialDesignLibrary.Resource.Id.dialog_rootView = global::MaterialDesignLibrary.Example.Resource.Id.dialog_rootView;
			global::MaterialDesignLibrary.Resource.Id.green = global::MaterialDesignLibrary.Example.Resource.Id.green;
			global::MaterialDesignLibrary.Resource.Id.message = global::MaterialDesignLibrary.Example.Resource.Id.message;
			global::MaterialDesignLibrary.Resource.Id.message_scrollView = global::MaterialDesignLibrary.Example.Resource.Id.message_scrollView;
			global::MaterialDesignLibrary.Resource.Id.number_indicator_spinner_content = global::MaterialDesignLibrary.Example.Resource.Id.number_indicator_spinner_content;
			global::MaterialDesignLibrary.Resource.Id.progressBarCircularIndetermininate = global::MaterialDesignLibrary.Example.Resource.Id.progressBarCircularIndetermininate;
			global::MaterialDesignLibrary.Resource.Id.red = global::MaterialDesignLibrary.Example.Resource.Id.red;
			global::MaterialDesignLibrary.Resource.Id.rootSelector = global::MaterialDesignLibrary.Example.Resource.Id.rootSelector;
			global::MaterialDesignLibrary.Resource.Id.shape_bacground = global::MaterialDesignLibrary.Example.Resource.Id.shape_bacground;
			global::MaterialDesignLibrary.Resource.Id.snackbar = global::MaterialDesignLibrary.Example.Resource.Id.snackbar;
			global::MaterialDesignLibrary.Resource.Id.text = global::MaterialDesignLibrary.Example.Resource.Id.text;
			global::MaterialDesignLibrary.Resource.Id.title = global::MaterialDesignLibrary.Example.Resource.Id.title;
			global::MaterialDesignLibrary.Resource.Id.viewColor = global::MaterialDesignLibrary.Example.Resource.Id.viewColor;
			global::MaterialDesignLibrary.Resource.Layout.color_selector = global::MaterialDesignLibrary.Example.Resource.Layout.color_selector;
			global::MaterialDesignLibrary.Resource.Layout.dialog = global::MaterialDesignLibrary.Example.Resource.Layout.dialog;
			global::MaterialDesignLibrary.Resource.Layout.number_indicator_spinner = global::MaterialDesignLibrary.Example.Resource.Layout.number_indicator_spinner;
			global::MaterialDesignLibrary.Resource.Layout.progress_dialog = global::MaterialDesignLibrary.Example.Resource.Layout.progress_dialog;
			global::MaterialDesignLibrary.Resource.Layout.snackbar = global::MaterialDesignLibrary.Example.Resource.Layout.snackbar;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_animate = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_animate;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_check = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_check;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_checkBoxSize = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_checkBoxSize;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_clickAfterRipple = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_clickAfterRipple;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_iconDrawable = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_iconDrawable;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_iconSize = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_iconSize;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_max = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_max;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_min = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_min;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_progress = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_progress;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_ringWidth = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_ringWidth;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_rippleBorderRadius = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_rippleBorderRadius;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_rippleColor = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_rippleColor;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_rippleSpeed = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_rippleSpeed;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_showNumberIndicator = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_showNumberIndicator;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_thumbSize = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_thumbSize;
			global::MaterialDesignLibrary.Resource.Styleable.CustomAttributes_value = global::MaterialDesignLibrary.Example.Resource.Styleable.CustomAttributes_value;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int dialog_main_hide_amination = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dialog_main_show_amination = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dialog_root_hide_amin = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_root_show_amin = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int progress_indeterminate_animation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int snackbar_hide_animation = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int snackbar_show_animation = 2130968582;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000d
			public const int animate = 2130771981;
			
			// aapt resource value: 0x7f010008
			public const int check = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int checkBoxSize = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int clickAfterRipple = 2130771983;
			
			// aapt resource value: 0x7f01000b
			public const int iconDrawable = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int iconSize = 2130771980;
			
			// aapt resource value: 0x7f010003
			public const int max = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int min = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int progress = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int ringWidth = 2130771975;
			
			// aapt resource value: 0x7f01000e
			public const int rippleBorderRadius = 2130771982;
			
			// aapt resource value: 0x7f010000
			public const int rippleColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int rippleSpeed = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int showNumberIndicator = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int thumbSize = 2130771978;
			
			// aapt resource value: 0x7f010005
			public const int value = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int green = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int thumbColor = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_button_float = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_button_rectangle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_checkbox = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background_checkbox_check = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int background_checkbox_uncheck = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int background_progress = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int background_switch_ball_uncheck = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int background_transparent = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blue_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dialog_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int float_button1_shadowp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int float_button_shadow1 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_action_new = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_launcher = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_next = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_reloj_max = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icn_button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int icn_progress = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icn_select_color = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icn_switch = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icn_widget = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int selector_list = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int shadow_down = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int shadow_right = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int sprite_check = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int transparent_backgrouns = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080019
			public const int blue = 2131230745;
			
			// aapt resource value: 0x7f080001
			public const int button = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int buttonColorSelector = 2131230725;
			
			// aapt resource value: 0x7f080013
			public const int buttonDialog = 2131230739;
			
			// aapt resource value: 0x7f080004
			public const int buttonFloat = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int buttonFloatSmall = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int buttonIcon = 2131230723;
			
			// aapt resource value: 0x7f080012
			public const int buttonSnackBar = 2131230738;
			
			// aapt resource value: 0x7f080020
			public const int button_accept = 2131230752;
			
			// aapt resource value: 0x7f08001f
			public const int button_cancel = 2131230751;
			
			// aapt resource value: 0x7f080000
			public const int buttonflat = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int checkBox = 2131230736;
			
			// aapt resource value: 0x7f08001b
			public const int contentDialog = 2131230747;
			
			// aapt resource value: 0x7f080015
			public const int contentSelector = 2131230741;
			
			// aapt resource value: 0x7f08001a
			public const int dialog_rootView = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int green = 2131230744;
			
			// aapt resource value: 0x7f080006
			public const int itemButtons = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int itemProgress = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int itemSwitches = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int itemWidgets = 2131230729;
			
			// aapt resource value: 0x7f08001e
			public const int message = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int message_scrollView = 2131230749;
			
			// aapt resource value: 0x7f080021
			public const int number_indicator_spinner_content = 2131230753;
			
			// aapt resource value: 0x7f08000a
			public const int progressBarCircularIndetermininate = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int progressBarIndeterminate = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int progressBarIndeterminateDeterminate = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int progressDeterminate = 2131230733;
			
			// aapt resource value: 0x7f080017
			public const int red = 2131230743;
			
			// aapt resource value: 0x7f080014
			public const int rootSelector = 2131230740;
			
			// aapt resource value: 0x7f080024
			public const int shape_bacground = 2131230756;
			
			// aapt resource value: 0x7f08000e
			public const int slider = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int sliderNumber = 2131230735;
			
			// aapt resource value: 0x7f080022
			public const int snackbar = 2131230754;
			
			// aapt resource value: 0x7f080011
			public const int switchView = 2131230737;
			
			// aapt resource value: 0x7f080023
			public const int text = 2131230755;
			
			// aapt resource value: 0x7f08001c
			public const int title = 2131230748;
			
			// aapt resource value: 0x7f080016
			public const int viewColor = 2131230742;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_buttons = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_progress = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_switchs = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_widgets = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int color_selector = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int number_indicator_spinner = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int progress_dialog = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int snackbar = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CustomAttributes = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 13
			public const int CustomAttributes_animate = 13;
			
			// aapt resource value: 8
			public const int CustomAttributes_check = 8;
			
			// aapt resource value: 9
			public const int CustomAttributes_checkBoxSize = 9;
			
			// aapt resource value: 15
			public const int CustomAttributes_clickAfterRipple = 15;
			
			// aapt resource value: 11
			public const int CustomAttributes_iconDrawable = 11;
			
			// aapt resource value: 12
			public const int CustomAttributes_iconSize = 12;
			
			// aapt resource value: 3
			public const int CustomAttributes_max = 3;
			
			// aapt resource value: 4
			public const int CustomAttributes_min = 4;
			
			// aapt resource value: 6
			public const int CustomAttributes_progress = 6;
			
			// aapt resource value: 7
			public const int CustomAttributes_ringWidth = 7;
			
			// aapt resource value: 14
			public const int CustomAttributes_rippleBorderRadius = 14;
			
			// aapt resource value: 0
			public const int CustomAttributes_rippleColor = 0;
			
			// aapt resource value: 1
			public const int CustomAttributes_rippleSpeed = 1;
			
			// aapt resource value: 2
			public const int CustomAttributes_showNumberIndicator = 2;
			
			// aapt resource value: 10
			public const int CustomAttributes_thumbSize = 10;
			
			// aapt resource value: 5
			public const int CustomAttributes_value = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
