#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlowLayout.Example.Resource", IsApplication=true)]

namespace FlowLayout.Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FlowLayout.Resource.String.ApplicationName = global::FlowLayout.Example.Resource.String.ApplicationName;
			global::FlowLayout.Resource.String.Hello = global::FlowLayout.Example.Resource.String.Hello;
			global::FlowLayout.Resource.Styleable.FlowLayout = global::FlowLayout.Example.Resource.Styleable.FlowLayout;
			global::FlowLayout.Resource.Styleable.FlowLayout_android_gravity = global::FlowLayout.Example.Resource.Styleable.FlowLayout_android_gravity;
			global::FlowLayout.Resource.Styleable.FlowLayout_Layout = global::FlowLayout.Example.Resource.Styleable.FlowLayout_Layout;
			global::FlowLayout.Resource.Styleable.FlowLayout_Layout_android_layout_gravity = global::FlowLayout.Example.Resource.Styleable.FlowLayout_Layout_android_layout_gravity;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int holo_blue_dark = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int button = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int button1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int button2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int button3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int flow = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_all_in_one = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_basic = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_scroll = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_visibility = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int activity_all_in_one = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int activity_basic = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int activity_scroll = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int activity_visibility = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int ExampleTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlowLayout = new int[] {
					16842927};
			
			// aapt resource value: 0
			public const int FlowLayout_android_gravity = 0;
			
			public static int[] FlowLayout_Layout = new int[] {
					16842931};
			
			// aapt resource value: 0
			public const int FlowLayout_Layout_android_layout_gravity = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
