#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidFlowLayout.Example.Resource", IsApplication=true)]

namespace AndroidFlowLayout.Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidFlowLayout.Resource.Attribute.debugDraw = global::AndroidFlowLayout.Example.Resource.Attribute.debugDraw;
			global::AndroidFlowLayout.Resource.Attribute.layoutDirection = global::AndroidFlowLayout.Example.Resource.Attribute.layoutDirection;
			global::AndroidFlowLayout.Resource.Attribute.layout_newLine = global::AndroidFlowLayout.Example.Resource.Attribute.layout_newLine;
			global::AndroidFlowLayout.Resource.Attribute.layout_weight = global::AndroidFlowLayout.Example.Resource.Attribute.layout_weight;
			global::AndroidFlowLayout.Resource.Attribute.weightDefault = global::AndroidFlowLayout.Example.Resource.Attribute.weightDefault;
			global::AndroidFlowLayout.Resource.Id.ltr = global::AndroidFlowLayout.Example.Resource.Id.ltr;
			global::AndroidFlowLayout.Resource.Id.rtl = global::AndroidFlowLayout.Example.Resource.Id.rtl;
			global::AndroidFlowLayout.Resource.String.ApplicationName = global::AndroidFlowLayout.Example.Resource.String.ApplicationName;
			global::AndroidFlowLayout.Resource.String.Hello = global::AndroidFlowLayout.Example.Resource.String.Hello;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_android_gravity = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_android_gravity;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_android_orientation = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_android_orientation;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_debugDraw = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_debugDraw;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_layoutDirection = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_layoutDirection;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_weightDefault = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_weightDefault;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_LayoutParams = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_LayoutParams;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_LayoutParams_android_layout_gravity = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_LayoutParams_android_layout_gravity;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_LayoutParams_layout_newLine = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_LayoutParams_layout_newLine;
			global::AndroidFlowLayout.Resource.Styleable.FlowLayout_LayoutParams_layout_weight = global::AndroidFlowLayout.Example.Resource.Styleable.FlowLayout_LayoutParams_layout_weight;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int debugDraw = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int layoutDirection = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int layout_newLine = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int layout_weight = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int weightDefault = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int flowLayout = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int ltr = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int rtl = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int button_horizontalMargin = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int button_longTest = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int button_newLine = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int button_test = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int button_verticalMargin = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FlowLayout = new int[] {
					16842927,
					16842948,
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int FlowLayout_android_gravity = 0;
			
			// aapt resource value: 1
			public const int FlowLayout_android_orientation = 1;
			
			// aapt resource value: 3
			public const int FlowLayout_debugDraw = 3;
			
			// aapt resource value: 2
			public const int FlowLayout_layoutDirection = 2;
			
			// aapt resource value: 4
			public const int FlowLayout_weightDefault = 4;
			
			public static int[] FlowLayout_LayoutParams = new int[] {
					16842931,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public const int FlowLayout_LayoutParams_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int FlowLayout_LayoutParams_layout_newLine = 1;
			
			// aapt resource value: 2
			public const int FlowLayout_LayoutParams_layout_weight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
