#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidStaggeredGrid.Example.Resource", IsApplication=true)]

namespace AndroidStaggeredGrid.Example
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidStaggeredGrid.Resource.Attribute.column_count = global::AndroidStaggeredGrid.Example.Resource.Attribute.column_count;
			global::AndroidStaggeredGrid.Resource.Attribute.column_count_landscape = global::AndroidStaggeredGrid.Example.Resource.Attribute.column_count_landscape;
			global::AndroidStaggeredGrid.Resource.Attribute.column_count_portrait = global::AndroidStaggeredGrid.Example.Resource.Attribute.column_count_portrait;
			global::AndroidStaggeredGrid.Resource.Attribute.grid_paddingBottom = global::AndroidStaggeredGrid.Example.Resource.Attribute.grid_paddingBottom;
			global::AndroidStaggeredGrid.Resource.Attribute.grid_paddingLeft = global::AndroidStaggeredGrid.Example.Resource.Attribute.grid_paddingLeft;
			global::AndroidStaggeredGrid.Resource.Attribute.grid_paddingRight = global::AndroidStaggeredGrid.Example.Resource.Attribute.grid_paddingRight;
			global::AndroidStaggeredGrid.Resource.Attribute.grid_paddingTop = global::AndroidStaggeredGrid.Example.Resource.Attribute.grid_paddingTop;
			global::AndroidStaggeredGrid.Resource.Attribute.item_margin = global::AndroidStaggeredGrid.Example.Resource.Attribute.item_margin;
			global::AndroidStaggeredGrid.Resource.String.ApplicationName = global::AndroidStaggeredGrid.Example.Resource.String.ApplicationName;
			global::AndroidStaggeredGrid.Resource.String.Hello = global::AndroidStaggeredGrid.Example.Resource.String.Hello;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView_column_count = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView_column_count;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView_column_count_landscape = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView_column_count_landscape;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView_column_count_portrait = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView_column_count_portrait;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView_grid_paddingBottom = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView_grid_paddingBottom;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView_grid_paddingLeft = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView_grid_paddingLeft;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView_grid_paddingRight = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView_grid_paddingRight;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView_grid_paddingTop = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView_grid_paddingTop;
			global::AndroidStaggeredGrid.Resource.Styleable.StaggeredGridView_item_margin = global::AndroidStaggeredGrid.Example.Resource.Styleable.StaggeredGridView_item_margin;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int column_count = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int column_count_landscape = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int column_count_portrait = 2130771969;
			
			// aapt resource value: 0x7f010007
			public const int grid_paddingBottom = 2130771975;
			
			// aapt resource value: 0x7f010004
			public const int grid_paddingLeft = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int grid_paddingRight = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int grid_paddingTop = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int item_margin = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int blue = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int green = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int grey = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int list_item_pressed = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int orange = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int red = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int yellow = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int list_item_selector = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090009
			public const int btn_go = 2131296265;
			
			// aapt resource value: 0x7f090004
			public const int btn_listview = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int btn_sgv = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int btn_sgv_empty_view = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int btn_sgv_fragment = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int col1 = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int col2 = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int col3 = 2131296269;
			
			// aapt resource value: 0x7f090005
			public const int grid_view = 2131296261;
			
			// aapt resource value: 0x7f090000
			public const int list_view = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int panel_content = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int reload = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int txt_line1 = 2131296264;
			
			// aapt resource value: 0x7f090006
			public const int txt_title = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int grid_column_count = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_list_view = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_sgv = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_sgv_empy_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list_item_header_footer = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int list_item_sample = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_sgv_empty_view = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int menu_sgv_dynamic = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] StaggeredGridView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public const int StaggeredGridView_column_count = 0;
			
			// aapt resource value: 2
			public const int StaggeredGridView_column_count_landscape = 2;
			
			// aapt resource value: 1
			public const int StaggeredGridView_column_count_portrait = 1;
			
			// aapt resource value: 7
			public const int StaggeredGridView_grid_paddingBottom = 7;
			
			// aapt resource value: 4
			public const int StaggeredGridView_grid_paddingLeft = 4;
			
			// aapt resource value: 5
			public const int StaggeredGridView_grid_paddingRight = 5;
			
			// aapt resource value: 6
			public const int StaggeredGridView_grid_paddingTop = 6;
			
			// aapt resource value: 3
			public const int StaggeredGridView_item_margin = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
